title: Zee Setash # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I was a teacher for four years, but I realized it wasn't the right fit for me. I discovered a love of data analysis and decided to start a new career. I am excited to put my new skills to use. 
  <br><br>
  <a href="https://www.linkedin.com/in/zee-setash-316516228//">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

